### ISSUE TITLE
Add qgroundcontrol

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#216]

**Comment by fnoop** [comment]
Like apmplanner2 requires qt5 which conflicts with ocam.

**Comment by fnoop** [comment]
Shelving to wishlist
https://github.com/fnoop/maverick/wiki/Wishlist

**Comment by fnoop** [comment]
Useful when using maverick on the desktop

**Comment by siliconalchemy** [comment]
Building qt on the pi is going to be hard.  Try qtrpi build:
http://www.qtrpi.com/download

**Comment by siliconalchemy** [comment]
Building qt on the pi is going to be hard. Try qtrpi build:
http://www.qtrpi.com/download

**Comment by fnoop** [comment]
Build qt from source, lock to 5.9.1
https://wiki.qt.io/Building_Qt_5_from_Git

**Comment by fnoop** [comment]
Looked at qtrpi, doesn't look like it's up to date enough, or provides enough of qt to use

**Comment by fnoop** [comment]
qt5 takes colossal resources to compile, 25gb+.  Work out smaller subset of qt5 modules to compile.

**Comment by fnoop** [comment]
Rejecting, as far too difficult to build.
