### ISSUE TITLE
Change ROS source install to desktop

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#424]
ROS source install is currently ros_comm, which does not include rviz and other desktop tools.

**Comment by khancyr** [comment]
@fnoop the recommended default for ROS should be ros-base . That way you have all stuff to start but without graphical thing that won't work on small platform

**Comment by fnoop** [comment]
Yes you're right I think!  All of the downloadable Maverick OS images are designed to be desktop capable/useful, so I thought adding a ROS desktop install would be useful for rviz etc.  However it drags in a whole crapload of dependencies including gazebo.  Which would be fine except they take up a huge amount of space and push the OS images over an 8Gb boundary, which seems like a sensible maximum.
