### ISSUE TITLE
Add support for PX4

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#483]

**Comment by cglusky** [comment]
some nice detailed info on PX4 offboard...

https://uav-lab.org/tutorials/software/

**Comment by fnoop** [comment]
https://dev.px4.io/en/setup/dev_env_linux_ubuntu.html
https://dev.px4.io/en/simulation/

**Comment by fnoop** [comment]
Basic support for compiling px4 added. Off by default, localconf param to enable:
```"maverick_dev::px4": true```
Compiles sitl firmware by default.  To enable cross compile for pixhawk etc, set localconf param:
```	"maverick_dev::px4::cross_compile": true```

**Comment by fnoop** [comment]
Looks like px4 doesn't have a built in SITL simulator like ardupilot, which will make running out of the box SITL difficult.

**Comment by fnoop** [comment]
http://discuss.px4.io/t/lightweight-or-command-line-sitl-simulation-options/2285/8

**Comment by SamuelDudley** [comment]
Running gazebo headless:
http://answers.gazebosim.org/question/18553/option-to-disabe-rendering-in-gazebo-8/
