### ISSUE TITLE
Network: Cannot set network interface parameters

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#606]
Cannot set interface parameters like frequency, power, rate etc

**Comment by cglusky** [comment]
Found an interesting code snippet over here...

https://github.com/dhalperi/linux-80211n-csitool-supplementary/issues/165

**Comment by fnoop** [comment]
@cglusky Thanks that was very useful, have used the idea during network refactor.

**Comment by fnoop** [comment]
`maverick netinfo` reports 2.412ghz frequency, even when changed successfully through iwconfig

**Comment by cglusky** [comment]
that code looks great.  very defensive.
