### ISSUE TITLE
Resize expansion must have failed

### ISSUE THREAD

**Issue by aidanjones3** [goodrobots/maverick#728]
Having difficulties installing other drivers for a camera to use ORB SLAM2. Realized that the resize of the root partiition must have failed. Log file shown below. Any help would be greatly appreciated.

[maverick.dev.2018-02-06-21-37.log](https://github.com/goodrobots/maverick/files/1700889/maverick.dev.2018-02-06-21-37.log)

**Comment by fnoop** [comment]
Hi, could you please run ~/software/maverick/manifests/maverick-modules/maverick_hardware/acts.d/odroid.py and post the output here?

**Comment by aidanjones3** [comment]
Will post the output later today, apologize for the delay.

**Comment by fnoop** [comment]
Please reopen if this is still a problem, works fine on all my testing

**Comment by edwinmora** [comment]
I had this same issue. i followed the install isntructions on the goodrobots site. here is my output when i run the python script:

odroid_kernel_install_flag=no
odroid_cpucores=8
odroid_kernel4x_release=no
odroid_kernel4x_dir=no
odroid_kernel3x_backups=no
odroid_kernel_current=no
odroid_swap=0 kB
odroid_memory=2043956 kB
odroid_model=Odroid XU4
odroid_sdsize=59688
odroid_present=yes
odroid_revision=0100
