### ISSUE TITLE
Bluetooth  can‘t work  after install  maverick  

### ISSUE THREAD

**Issue by HubFire** [goodrobots/maverick#753]
Bluetooth  work well on  raspbian  jessie  ,but after i  install  maverick  , can  not find  bluetooth device . my computer is  raspberry  zero  W  .  how can  i  make  bluetooth  work  on  maverick

**Comment by HubFire** [comment]
Thank you very much !   So，how can I  use  bluetooth  in maverick ?

**Comment by HubFire** [comment]
I added a  serial -to-bluetooth module  on the  flight control, and I want to send mavlink instructions to the flight control via Bluetooth。

**Comment by fnoop** [comment]
Ah right, interesting.  OK I'll add an option to turn it back on.

**Comment by HubFire** [comment]
OK， thank  you!
