### ISSUE TITLE
LIBUSB_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by Merkensen** [goodrobots/maverick#776]
Hi,
I would like to use the Thermal Seek Compact Pro with maverick on a Raspberry Pi 3 B but vision_seek stopped working after a few seconds. I hope you can help me.
maverick version is 1.1.6 flashed with Etcher

[dev] [mav@maverick-raspberry ~]$ maverick log vision_seek                                     
                                                                                                
Maverick - UAV Companion Computer System - Version 1.1.6                                        
                                                                                                
Displaying service log: vision_seek                                                             
-- Logs begin at Thu 2016-11-03 17:16:42 GMT. --                                                
May 30 12:01:00 maverick-raspberry systemd[1]: Started Maverick - Seek Thermal Vision.          
May 30 12:01:00 maverick-raspberry vision_seek.sh[2542]: /srv/maverick/software/libseek-thermal/
bin/seek_viewer --fps=7 --scale=1.0 --colormap=2 --rotate=90 --camtype=seekpro -o /srv/maverick/
data/vision/vision_seek/seek.avi                                                                
May 30 12:01:05 maverick-raspberry vision_seek.sh[2542]: Video stream created, dimension: 240x32
0, fps:7                                                                                        
May 30 12:01:28 maverick-raspberry vision_seek.sh[2542]: Error: bulk transfer failed: LIBUSB_ERR
OR_TIMEOUT                                                                                      
May 30 12:01:28 maverick-raspberry vision_seek.sh[2542]: Error: frame acquisition failed

**Comment by fnoop** [comment]
Hi @Merkensen this is down to usb timing (raspberry is known to be poor with usb).  You can try unplugging and replugging, or rebooting the raspberry.  If it persists, suggest you raise an issue with the project that deals with the actual communication with the seek:
https://github.com/maartenvds/libseek-thermal/issues
