### ISSUE TITLE
Document custom maverick module

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#797]
eg. how to create a custom module to add a second SITL instance

**Comment by fnoop** [comment]
And is there somewhere outside of ~/software/maverick that a custom module can be placed?  ~/software/maverick is goodrobots git repo, either a custom module directory can be .gitignored, or probably better a separate area in ~/code should be setup.

**Comment by fnoop** [comment]
Add two locations for custom modules:
 - ~/software/maverick/manifests/custom-modules
 - ~/code/maverick/custom-modules

**Comment by fnoop** [comment]
Interface stats added to stats module.

**Comment by fnoop** [comment]
Oops, wrong repo

**Comment by fnoop** [comment]
Added support for the new module locations.  Just need to document.

**Comment by rgreenosborne** [comment]
https://github.com/rgreenosborne/maverick/blob/master/docs/next/modules/custom.md
      
@fnoop Am I doing this right?  do you have a code block for an actual second SITL module? Git is so damned intimidating.
