### ISSUE TITLE
Grafana fails to install

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick#806]
__Issue:__ Running `maverick configure` graphana fails to install
__Env:__ maverick current master on Pi3b+
__Cause:__ `latest` is being used in the download url
__Fix:__ change `$grafana_version = latest,` to `$grafana_version = '5.1.4',`

**Comment by fnoop** [comment]
The old thirdparty source for raspberry packages has stopped, but grafana is producing arm packages now, so switch all sources to grafana packages.
They provide an apt repo now:
http://docs.grafana.org/installation/debian/

Only armv7 unfortunately so we'll have to drop support for rpi zero.

I think we'll stop using grafana shortly anyway as it doesn't support integration - it demands to be used as a complete interface.

**Comment by fnoop** [comment]
Latest grafana 6.0.2 doesn't work with the existing config, but latest 5.0 (5.4.3) version does so fixing that.
