### ISSUE TITLE
Opencv fails to build

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick#808]
__Issue:__ Running `maverick configure` fails during the opencv build. All vision code subsequently fails.
See attached log files:
https://files.gitter.im/goodrobots/dev/Lkew/maverick.dev.2019-01-13-03-07.log
https://files.gitter.im/goodrobots/dev/LCv0/CMakeOutput.log__1_.tar.gz

__Env:__ Current maverick master on a Pi3b+

__Notes:__ Unsure where to begin fixing this one, but it sure would be great to sort out!

**Comment by SamuelDudley** [comment]
Some more info on this.... it was `opencv_dldt` failing in `opencv_dldt-prepbuild`

**Comment by fnoop** [comment]
Ah that's openvino: https://github.com/goodrobots/maverick/issues/791

This has been resolved by the upstream project now

**Comment by fnoop** [comment]
Wow my issue really opened a can of worms!  They haven't tagged the R5 release in github so I'll just change the reference to master for now.

**Comment by fnoop** [comment]
Although it should be fixed and compile, openvino is now turned off by default anyway, as it is of limited use without specific hardware requirements.
