### ISSUE TITLE
is this project still alive? / will be continued?

### ISSUE THREAD

**Issue by p3pp0** [goodrobots/maverick#812]
would like to now... :-)

**Comment by fnoop** [comment]
Hi @p3pp0 Yes very much still alive :)  But we've been very bad at updating/responding to issues in this repo, as you've found we're working very hard on the web frontend and GCS.  Hopefully will have some update soon, my plan is to release a Maverick 2.0 with the prototype of the web frontend and the base networking refactored in not toooo long a time frame :)

**Comment by p3pp0** [comment]
Nice to heat @fnoop :-)

i am excited about the update and will be one of the first beta testers ;-) is there like a newsletter were i can subscribe to to get informed if you guys are ready? :-)
