### ISSUE TITLE
Add support for intel realsense sdk 2

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#815]
Support is currently for realsense sdk 1 which supports legacy hardware such as r200.  Add sdk 2 which supports newer d400 and t260 hardware.
Should ideally support both as options simultaneously.

**Comment by fnoop** [comment]
This is the legacy branch:
https://github.com/IntelRealSense/librealsense/tree/legacy

This is the new branch (sdk2):
https://github.com/IntelRealSense/librealsense/tree/master

**Comment by alchemyconsulting** [comment]
So realsense currently exists in:
 maverick_hardware::peripheral::realsense
and
 maverick_vision::realsense

Originally librealsense and realsense-sdk (and samples) were separate projects and installs.  Now librealsense is the sdk as well, so we should get rid of one of them.  Which one?

**Comment by fnoop** [comment]
So realsense currently exists in:
maverick_hardware::peripheral::realsense
and
maverick_vision::realsense

Originally librealsense and realsense-sdk (and samples) were separate projects and installs. Now librealsense is the sdk as well, so we should get rid of one of them. Which one?

Keep maverick_hardware, ditch maverick_vision

**Comment by fnoop** [comment]
Python wrapper:
https://github.com/IntelRealSense/librealsense/tree/development/wrappers/python
