### ISSUE TITLE
visiond service on RPI Zero failing

### ISSUE THREAD

**Issue by HSVILJOEN** [goodrobots/maverick#830]
Trying to start visiond service to be able to stream seek thermal camera through RTSP, but service is not starting up:

maverick v 1.5.5 

Apr 22 13:24:13 maverick-raspberrylite maverick-visiond[2077]: Starting maverick-visiond
Apr 22 13:24:14 maverick-raspberrylite systemd[1]: maverick-visiond.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 13:24:14 maverick-raspberrylite systemd[1]: maverick-visiond.service: Unit entered failed state.
Apr 22 13:24:14 maverick-raspberrylite systemd[1]: maverick-visiond.service: Failed with result 'exit-code'.
Apr 22 13:24:44 maverick-raspberrylite systemd[1]: maverick-visiond.service: Service hold-off time over, scheduling restart.
Apr 22 13:24:44 maverick-raspberrylite systemd[1]: Stopped Maverick Vision Daemon.

Config file attached.
[maverick-visiond.conf.txt](https://github.com/goodrobots/maverick/files/3103346/maverick-visiond.conf.txt)

**Comment by fnoop** [comment]
Hi @HSVILJOEN could you please attach a log file from ~/var/log/vision?

**Comment by fnoop** [comment]
Confirmed working with maverick 2.0, will release a beta soon.
