### ISSUE TITLE
Add parameter to increase file watchers for vscode

### ISSUE THREAD

**Issue by alchemyconsulting** [goodrobots/maverick#850]
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by alchemyconsulting** [comment]
There is an error when connecting vscode

**Comment by fnoop** [comment]
This already exists in maverick_web/manifests/codeserver.pp, which is probably best deprecated now.  Added maverick_dev::vscode_watchers parameter.
