### ISSUE TITLE
Lock down grafana version

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#860]
If we're going to keep grafana, then at least lock down the package version.  At the moment we specify a version (because the api keeps changing), but then apt keeps updating it to the latest.  Either pin the pkg, build from source, or better yet just remove grafana.

**Comment by SamuelDudley** [comment]
I quite like the graphics it produces visually but if I recall you were having issues taking the elements and displaying them in a custom view?

I'm personally willing to explore other options if you would like to drop it.

**Comment by fnoop** [comment]
Use apt-mark to hold the version

**Comment by fnoop** [comment]
Added bit of code but commented out, to hold grafana package, as it causes a puppet loop as grafana module can't cope with held packages.

Not worth the effort, grafana will probably disappear and this is an annoyance.
