### ISSUE TITLE
Broken link to Odroid XU4 image in the documentation

### ISSUE THREAD

**Issue by hflemmen** [goodrobots/maverick#884]
Hi!

The link "[Odroid XU3/XU4 - 1.0.4 - {d5bb5cd9c70273148d8c0bf9078ba85ce093589b13031c8ae94f8393fc51de86}](http://www.maverick.one/maverick/downloads/maverick-1.0.4-odroidxu4.img.xz)"  on the quick start page: [OS images](https://goodrobots.github.io/maverick/current/#/?id=os-images) returns 404 for me.

**Comment by fnoop** [comment]
Hi @hflemmen thanks for pointing that out!  We dropped the downloads for odroid and joule a while back but forgot to remove the doc links.
The odroid support should still work (but might need a few tweaks), but you'd have to build it yourself:
https://goodrobots.github.io/maverick/current/#/?id=bootstrap-maverick
