### ISSUE TITLE
Question?... using this to stream SEEK thermal video from a mavic mini?

### ISSUE THREAD

**Issue by russr123** [goodrobots/maverick#886]
i have a mini usb seek compact pro, and a mavic mini... what's the best way to get this done?

what's needed? parts list?

**Comment by fnoop** [comment]
Sorry, you would need a companion computer (like a raspberry pi zero) at least, and currently Maverick only deals with Mavlink UAVs like Ardupilot/PX4.  We'd like to support DJI craft in the future but at the moment it's not possible/feasible.
