### ISSUE TITLE
api@maverick still exists and is fighting api@system for ports

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick#938]
currently api@maverick is fighting api@system for port 6700. I'm pretty sure api@maverick was meant to be removed and replaced with api@system, however both exist after a configure run.

**Comment by fnoop** [comment]
yeah that was a bit lazy, but api@maverick only existed for a short period in master so unlikely anyone other than you or me have seen it.  Just stop and disable the service.
