### ISSUE TITLE
webrtc stream fails first start

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#939]
See https://github.com/goodrobots/maverick-web/issues/172

**Comment by fnoop** [comment]
Changed boot order so webrtc starts after visiond in systemd startup, but needs more than that.  visiond takes time to startup the video stream and create a client, webrtc is starting before the stream starts, fails and doesn't retry.  Restarting webrtc later on correctly connects to the visiond rtsp stream and then works.

Need to somehow delay the webrtc startup until visiond rtsp stream is fully active.

**Comment by SamuelDudley** [comment]
https://github.com/facebookincubator/pystemd/blob/master/_docs/daemon.md

We can use pystemd to notify systemd when the stream is created. Webrtc will wait until the notification occurs.

**Comment by fnoop** [comment]
Think this is fixed now

**Comment by SamuelDudley** [comment]
Interesting, this since your patch I have not been able to get a stream running. I can see that webrtc is trying to start but visiond was totally failing to start. Perhaps it's related to the http get in visond (janus thread) being made with webrtc not yet running? Need to have a closer look.

**Comment by fnoop** [comment]
What is the visiond log saying?

**Comment by SamuelDudley** [comment]
Visond is getting a connection refused error on line 86 of janus.py (the get_info request) which causes it to exit and retry. At the same time webrtc is in a loop not able to connect to the websocket handler (as visond has not started).

**Comment by SamuelDudley** [comment]
Possibly we could delay the get_info request until after the websock server has started?

**Comment by fnoop** [comment]
> Visond is getting a connection refused error on line 86 of janus.py (the get_info request) which causes it to exit and retry. At the same time webrtc is in a loop not able to connect to the websocket handler (as visond has not started).

Ah.  Odd I'm not getting that, but that's only there to query janus if it's already up and running, so just wrap it in a try/except.
visiond then starts up the websocket which janus connects to and fires events over.  The initial query is only for if janus is already running.

**Comment by SamuelDudley** [comment]
Sure thing. Leave it with me.

**Comment by fnoop** [comment]
Updated visiond, should work now

**Comment by fnoop** [comment]
It's looking for the other sample files that maverick is removing - ignore those warnings.

**Comment by SamuelDudley** [comment]
okay, turns out it was a mix of things..
`input = v4l2` is no longer a valid option in visiond and that was causing a failure. That was only a recent problem. The bigger problem was that the video streaming didnt work on linux + firefox or ios + chrome (ipad) so I was second guessing if webrtc was working as expected. Works fine (after fixing the visiond config file on linux + chrome.

**Comment by fnoop** [comment]
> input = v4l2 is no longer a valid option in visiond and that was causing a failure
oops, sorry - I normalised the inputs and changed all the configs, but forgot it would affect existing configs files.
The default now is to have a completely blank config and let everything autodetect.

**Comment by SamuelDudley** [comment]
I just wiped the config file and all was well 👍 I think the `input = v4l2` option is still floating around in there, just commented out. Are there any other options that if uncommented would cause problems?

**Comment by fnoop** [comment]
Oh yes, updated thanks!  I've been through all the other configs and changed all the defaults in visiond so I think they should be good.  v4l2 was 'wrong' to start with which is why I corrected it.
