### ISSUE TITLE
Apt missing package

### ISSUE THREAD

**Issue by norcaluav** [goodrobots/maverick#996]
Encountered this this afternoon, on a fresh flash of the raspberry pi image.

Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-gobject-dev' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package python-gobject-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-gobject-2-dev

E: Package 'python-gobject-dev' has no installation candidate
Error: /Stage[main]/Maverick_vision::Gstreamer/Package[python-gobject-dev]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-gobject-dev' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Package python-gobject-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-gobject-2-dev

E: Package 'python-gobject-dev' has no installation candidate

Hope it helps :)

**Comment by fnoop** [comment]
Thanks for reporting, sorry for the delay responding!  This shouldn't happen on a raspberry, it's not present/fixed on the latest builds now.
